version: 2

before:
  hooks:
    - go mod tidy

#env_files:
#  gitlab_token: ~/.jf_gitlab_token

builds:
  - id: "NewApp"
    main: ./cmd/app/
    binary: "NewApp"
    ldflags:
      - -s -w
      - -X 'main.buildTime={{.Date}}'
      - -X 'main.shortCommit={{.ShortCommit}}'
      - -X 'main.fullCommit={{.FullCommit}}'
      - -X 'main.version={{.Version}}'
    flags:
      - -trimpath
#    env:
#      - CGO_ENABLED=0
#      - GOARM64=v8.2
#    goos: [ linux ]
#    goarch: [ arm64 ]

# https://nfpm.goreleaser.com/configuration/
# https://goreleaser.com/customization/nfpm/

nfpms:
  - package_name: bf-application-name
    maintainer: 'Jeremy Foran <jeremy.foran@blueflag.consulting>'
    vendor: Blue Flag Consulting
    homepage: 'https://blueflag.consulting/'
    description: The Description goes here.
    license: Proprietary
    formats:
      - deb
    id: newApp
    dependencies:
#      - libssl-dev
    bindir: /usr/bin
    contents:
#      - src: ./assets/logrotate
#        dst: /etc/logrotate.d/photobooth
#      - src: ./assets/application.service
#        dst: /usr/lib/systemd/system/application.service
#      - src: ./configuration/example-config.yaml
#        dst: /etc/aperture/config.yaml
#        type: config|noreplace
#    scripts:
#      preinstall: assets/preinstall.sh
#      postinstall: assets/postinstall.sh
#      preremove: assets/preremove.sh
#      postremove: assets/postremove.sh

gitlab_urls:
  api: https://gitlab.jeremyforan.com/api/v4/
  download: https://gitlab.jeremyforan.com
  skip_tls_verify: false
  use_package_registry: true # Keep this for other GitLab integrations, but the 'publishers' section will handle Debian uploads.
